---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donger
  labels:
    app.kubernetes.io/name: donger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: donger
  template:
    metadata:
      labels:
        app.kubernetes.io/name: donger
    spec:
      containers:
        - name: donger
          image: donger
          env:
            - name: GOWON_BROKER
              value: mosquitto:1883
